### ISSUE TITLE
Probeer je code meer DRY te maken

### ISSUE THREAD

**Issue by joostf** [julesbruins/look-and-feel-corporate-identity#31]
https://github.com/julesbruins/look-and-feel-corporate-identity/blob/1077fb0563f0f75672f43d45f3847d7e759b8929/styles/dda-gezamenlijk.css#L47-L93

Dit kan je bijvoorbeeld doen door generieke properties eerst te definiëren voor alle betreffende elementen en daarna uitzonderingen per element.
```css
h1, h2, h3, h4, h5, h6 {
  font-size: clamp(2.5rem, 6vw, var(--size-l));
  font-weight: 600; 
  letter-spacing: var(--letter-spacing);
  line-height: clamp(1em, 5vw, var(--size-l));
  text-transform: uppercase;
}

h1 {
  font-size: clamp(2.5rem, 6vw, var(--size-xxl));
  line-height: clamp(1em, 5vw, var(--size-xxl));
}

....
```

Pro tip: maak gebruik van Pseudo Private Custom Properties om je code nog efficiënter en leesbaarder te maken: 

```css
h1, h2, h3, h4, h5, h6 {
  --_font-size: var(--size-l);

  font-size: clamp(2.5rem, 6vw, var(--_font-size);
  ...
}

h1 {
  --_font-size: var(--size-xxl);
  ....
}

....
```

Bron: https://lea.verou.me/blog/2021/10/custom-properties-with-defaults/
